// Woordenlijst Grieks per les (blz. 173–178), transcribed from img-greek/IMG_3672 … IMG_3677.
// Same line format as data.js:  greek [note] = meaning | sense 2 {italic remark}

const GREEK_LESSONS_RAW = [
{ id: "2", chapter: 2, kind: "les", subtitle: "Telwoorden 1–10", words: `
ἑπτά = zeven
δέκα = tien
τέτταρες = vier
δύο = twee
ἕξ = zes
τρεῖς = drie
εἷς = een
ἐννέα = negen
ὀκτώ = acht
πέντε = vijf
`},
{ id: "3", chapter: 3, kind: "les", words: `
ἀλλά, ἀλλ’ = maar
δέ, δ’ = en | maar {δέ staat meestal op de 2de, soms op de 3de plaats van de zin. Meestal kun je δέ onvertaald laten, behalve na een komma}
εἰσί(ν) = (zij) zijn
ὁ δοῦλος = slaaf
ὁ θεός = god
εἰς [+ acc.] = naar, naar binnen, tot
ἔχει = (hij, zij, het) heeft
ἐστί(ν) = (hij, zij, het) is
ἡ χώρα = land, streek
βαίνει = (hij, zij, het) gaat
γάρ = want {γάρ staat op de 2de plaats van de zin}
καί = en | ook | zelfs
λαμβάνει = (hij, zij, het) neemt, pakt (vast)
πρός [+ acc.] = naar(toe), tot
τί…; = waarom?
νῦν = nu
ὁ ἄνθρωπος = mens | man
ἔχουσι(ν) = (zij) hebben
φέρουσι(ν) = (zij) dragen | (zij) brengen
ποιοῦσι(ν) = (zij) doen | (zij) maken
βαίνουσι(ν) = (zij) gaan
ὁ δεσπότης = heerser, meester
φεύγουσι(ν) = (zij) vluchten (voor) {+ acc.}
λαμβάνουσι(ν) = (zij) nemen, pakken (vast)
οἰκεῖ = (hij, zij, het) woont, bewoont
φέρει = (hij, zij, het) draagt | (hij, zij, het) brengt
ἡ μάχη = gevecht, strijd
οὐ, οὐκ, οὐχ = niet
οὕτως, οὕτω = zo, op die manier
ὁ φόβος = angst, vrees
οἰκοῦσι(ν) = (zij) wonen, bewonen
ποιεῖ = (hij, zij, het) doet | (hij, zij, het) maakt
τὸ θηρίον (mv. τὰ θηρία) = wild dier, beest
τοῦτο = dit, dat {nom. + acc. onz.}
φεύγει [+ acc.] = (hij, zij, het) vlucht (voor)
`},
{ id: "4", chapter: 4, kind: "les", words: `
πρῶτον μὲν…, ἔπειτα δέ = eerst…, daarna
ἀθάνατος = onsterfelijk
αὐτίκα = meteen, onmiddellijk
δεινός, δεινή, δεινόν = verschrikkelijk, geducht
ἕκαστος, ἑκάστη, ἕκαστον = ieder
ἐνταῦθα = daar
κρύπτει = (hij) verbergt
ἔπειτα = daarna
ζητεῖ = (hij) zoekt
ἡ πέτρα = rots, rotsblok
ἀποκτείνει = (hij) doodt
καλεῖ = (hij) roept
μακρός, μακρά, μακρόν = lang
εὑρίσκει = (hij) vindt, ontdekt, treft aan
μέγας, μεγάλη, μέγα = groot
μέν = {geeft aan dat er nóg een zin komt; die tweede zin begint met δέ; μέν blijft onvertaald}
ἄλλος, ἄλλη, ἄλλο = ander
μία = één {vrouwelijk}
ἡ κεφαλή = hoofd, kop
νέος, νέα, νέον = nieuw | jong
οὐδέν = niets
θνητός = sterfelijk
ὁ φίλος = vriend
φοβερός, φοβερά, φοβερόν = angstaanjagend
τί…; = wat? | waarom?
`},
{ id: "5", chapter: 5, kind: "les", words: `
αἱ πύλαι = poort, ingang
τότε = dan, toen
αἰτέω [+ 2 acc.] = (iemand) vragen (om)
πολλοί = veel, velen
ἀνδρεῖος = dapper
ὅτι = dat {voegwoord} | omdat
αὐτῇ = (aan/voor) haar {dativus pers. vnw.}
ἐγώ = ik {pers. vnw.}
ἐθέλω = willen, bereid zijn
ἄγω (inf. ἄγειν) = brengen, leiden
ἐκ [+ gen.] = uit
κακός = slecht
ἐνθάδε = hier(heen)
ἔξεστι(ν) [+ dat. (+ inf.)] = het is (voor iemand) mogelijk/geoorloofd om
ἐπί [+ acc.] = op…af, naar
ἐπί [+ dat.] = bij, op, aan
ἐπιθυμέω [+ gen.] = verlangen (naar), begeren
ἡ βασίλεια = koningin
ἐν [+ dat.] = in, op, bij
ἡ θεός = godin
ἥκω = komen, gekomen zijn
αὐτήν = haar {accusativus pers. vnw.}
αὐτῆς = (van) haar {genitivus pers. vnw.}
αὐτόν = hem {accusativus pers. vnw.}
αὐτοῦ = (van) hem {genitivus pers. vnw.}
αὐτῷ = (aan/voor) hem {dativus pers. vnw.}
ἡ οἰκία = huis
θαυμάζω = bewonderen, zich verwonderen
ἰσχυρός = sterk, krachtig
κελεύω [+ acc. + inf.] = bevelen, verzoeken, vragen om
κρατέω [+ gen.] = macht hebben over, zich meester maken van, overwinnen
λέγω = zeggen
μάλα = erg, zeer {bijwoord}
μέλλω [+ inf.] = op het punt staan om, van plan zijn, zullen
μετά [+ gen.] = (samen) met
μοί, μοι = (aan/voor) mij/me {dativus pers. vnw.}
ὁ ἑταῖρος = vriend, makker
ὁ ἵππος = paard
ὅμοιος [+ dat.] = gelijk aan, gelijkend op
πέμπω (inf. πέμπειν) = sturen, zenden
ὁ νεκρός = lijk, dode
ὁ λόγος = woord
ὁ ξένος = vreemdeling
ὁ πόλεμος = oorlog
οὖν = dan, nu {als een verhaal verder gaat} | dus {in een conclusie}
παρέχω (inf. παρέχειν) = verschaffen, geven
σέ, σε = jou, je, u {accusativus pers. vnw.}
σός, σή, σόν = jouw, uw {bezittelijk vnw.}
σύ = jij, u {pers. vnw.}
τὰ ὅπλα = wapens
…τε καί… = en {verbindt twee woord(groep)en nauw met elkaar}
τὸ δῶρον = geschenk, cadeau
τὸ ἔργον = werk, daad
φιλέω = houden van, beminnen
λύω (inf. λύειν) = losmaken
φίλος = geliefd, dierbaar
καλός = mooi
`},
{ id: "6", chapter: 6, kind: "les", words: `
δακρύω = huilen
Ἀθηναῖος = Atheens
αἱ Ἀθῆναι = Athene {de stad}
αἴρω = optillen, oppakken
ὧδε = zo, als volgt
ἀκούω = horen | {+ gen., bij personen} horen, luisteren (naar)
γαμέω [+ acc.] = trouwen (met)
δή = {geeft nadruk} dan, dus {vaak moeilijk te vertalen}
μετά [+ acc.] = na
διά [+ acc.] = door, wegens
εἰ = als, indien
εἶναι = (te) zijn {infinitivus}
αὐτοῖς = (aan/voor) hen {dativus pers. vnw.}
ἐκβαίνω = gaan uit
ἐμέ, με = mij, me {accusativus pers. vnw.}
ἔξω = buiten
ἡ ἀνδρεία = moed, dapperheid
εἰσβαίνω = ingaan, komen in
ἡ θάλαττα = zee
ἡ λύπη = verdriet
ἡ θύρα = deur
ἡμεῖς = wij {pers. vnw.}
ἡμῖν = (aan/voor) ons {dativus pers. vnw.}
ὁ υἱός = zoon
ἡ νῆσος = eiland
εἰμί = ik ben
πρός [+ dat.] = bij
ἡ σωτηρία = redding, behoud
θαυμάζω ὅτι = zich erover verwonderen dat
ἡ βία = kracht, geweld
ἡ ἡμέρα = dag
καθεύδω = slapen
ἡμᾶς = ons {accusativus pers. vnw.}
λείπω = (ver)laten
μένω = blijven | {+ acc.} wachten (op)
μόνος = alleen
μου, ἐμοῦ = (van) mij, mijn {genitivus pers. vnw.}
ὁ Ἀθηναῖος = Athener
ὁ ἄνεμος = wind
τὸ τέκνον = kind
ὁ γάμος = huwelijk
ὁ χρόνος = tijd
πάλιν = weer, opnieuw | terug
μή = niet {bij gebiedende wijs}
πλέω = varen
σῴζω = redden
τὸ πλοῖον = schip
ὑμεῖς = jullie, u {pers. vnw.}
χαίρω [+ dat.] = blij zijn (met), zich verheugen (over)
`},
{ id: "7", chapter: 7, kind: "les", words: `
τίς…; = wie, wat? | welk(e)?
ἀεί = altijd
ἐπί [+ gen.] = op
ἀναβαίνω = omhoog gaan, beklimmen
μετὰ ταῦτα = na dit, daarna
ἀποθνῄσκω = sterven
ὁ βίος = leven
ἀποφέρω = wegbrengen, wegvoeren
αὐτός, αὐτή, αὐτό = zelf {bijvoeglijk gebruikt}
βλέπω = kijken
ἑαυτόν = zichzelf {accusativus}
αἴτιος [+ gen.] = verantwoordelijk voor, schuldig aan
ἐγείρω = (op)wekken, wakker maken
ἡ αἰτία = oorzaak
ἐμός, ἐμή, ἐμόν = mijn {bezittelijk vnw.}
ἡ ἐλευθερία = vrijheid
ἡ ἡδονή = genot, vreugde
ὁ θάνατος = de dood
ἑαυτῷ = (voor, tot, bij) zichzelf {dativus}
ἡ παρθένος = (ongetrouwd) meisje, maagd
ἡ φυγή = vlucht
ὁ ὕπνος = slaap
ἡ φωνή = stem
ἱερός = heilig | {+ gen.} gewijd aan
κατέχω = in zijn macht hebben, vasthouden, beheersen
μετέχω [+ gen.] = deelhebben aan, deelnemen aan
μόνον = slechts, alleen maar {bijwoord}
νομίζω = menen | {+ 2 acc.} beschouwen als, vinden
ὁ αὐτός = dezelfde
ὁ ἥλιος = zon
ὁ κίνδυνος = gevaar
ἀπό [+ gen.] = vanaf
ῥίπτω = werpen, gooien
ὁ οἶνος = wijn
οὐ μόνον…, ἀλλὰ καί = niet alleen…, maar ook
οὐδείς = niemand {lett. zelfs niet één}
περί [+ gen.] = om, over
αὖθις = opnieuw, weer
πίπτω = vallen
πλήν [+ gen.] = behalve
ἄνευ [+ gen.] = zonder
πολύς, πολλή, πολύ = veel
τυγχάνω [+ gen.] = treffen | krijgen
φροντίζω [+ gen.] = zich bekommeren om
ὥσπερ = zoals
ἡ συμφορά = gebeurtenis | ongeluk
`},
{ id: "8", chapter: 8, kind: "les", words: `
ἐν νῷ ἔχω = van plan zijn {lett. in de geest hebben}
ἀγγέλλω = berichten, melden
φίλτατος = liefst, dierbaarst | zeer/heel geliefd, zeer/heel dierbaar
ἀντί [+ gen.] = in plaats van
ἡ στρατιά = leger
βοηθέω [+ dat.] = te hulp komen, helpen
εὔνους [+ dat.] = goedgezind (aan)
παύω = (doen/laten) stoppen, (doen/laten) ophouden
ἐχθρός [+ dat.] = gehaat (bij), vijandig (aan)
ἡ ἀλήθεια = waarheid
ἤδη = al, reeds
κωλύω [+ inf.] = verhinderen, beletten (om)
ὁ ἄγγελος = bode
οἱ ἄνδρες (ἀνδρῶν) = mannen
ὁ πατήρ = vader
ἄθλιος = ongelukkig
ἅμα = tegelijk, tegelijkertijd
ὅμως = toch
ὁ ναύτης = zeeman, matroos
ὁ στρατηγός = legeraanvoerder
ὁ στρατιώτης = soldaat
πιστεύω [+ dat.] = vertrouwen
οὐδέ = en niet, maar niet | ook niet, zelfs niet
τόδε (onz.), mv. τάδε = dit | het volgende
οὐδέν = niets | helemaal niet
οὐκέτι = niet meer
πάρειμι = aanwezig zijn
ἡ τύχη = lot
πάντες (πάντων) = alle(n)
τοιοῦτος, τοιαύτη, τοιοῦτο = zodanig, dergelijk, zo’n {mnl., vrl., onz.}
ὁ νοῦς = geest, verstand
εἶχον = {imperfectum van ἔχω}
παρῆν = {imperfectum van πάρειμι}
ἀρέσκω [+ dat.] = bevallen aan, in de smaak vallen bij
`},
{ id: "9", chapter: 9, kind: "les", words: `
τὸ πῦρ (πυρός) = vuur
τὸ σῶμα (σώματος) = lichaam
ἀμφί [+ acc.] = rondom
ἄξιος [+ gen.] = waard, waardig
δεῦρο = hier(heen)
ἀποπέμπω = terugsturen, wegsturen
ὁ/ἡ παῖς (παιδός) = kind (jongen, meisje) | slaaf
ἄριστος = beste | zeer/heel goed
ἄφρων (ἄφρονος, nom. mv. ἄφρονες) = onverstandig, dwaas
ἐγγύς [+ gen.] = dichtbij
οἴκαδε = naar huis
ἕτοιμος [+ inf.] = bereid, gereed, klaar (om te)
ὑμέτερος = (van) jullie/u {bezittelijk voornaamwoord}
κομίζω = brengen, halen
ὁ λέων (λέοντος) = leeuw
εὐδαίμων (εὐδαίμονος, nom. mv. εὐδαίμονες) = gelukkig
ἡ γυνή (γυναικός) = vrouw
ἡ ἔρις (ἔριδος) = strijd, ruzie, twist
ἡμεῖς, ἡμῶν, ἡμῖν, ἡμᾶς = wij {nom., gen., dat., acc. pers. vnw.}
ἡμέτερος = ons, onze {bezittelijk voornaamwoord}
ἡ μήτηρ (μητρός) = moeder
καθίζω = (gaan) zitten
μέλει μοι = (het) interesseert me
μηκέτι = niet meer {bij gebiedende wijs}
ὁ ἀνήρ (ἀνδρός) = man
ἡ δόξα = mening | roem
ὁ ἡγεμών (ἡγεμόνος) = leider, aanvoerder
οἷός τέ εἰμι [+ inf.] = in staat zijn om, kunnen
ἐμοῦ, μου = (van) mij, mijn {genitivus pers. vnw.}
ὁ σῖτος = eten, voedsel
πείθω = overtuigen, overreden
ὁ σωτήρ (σωτῆρος) = redder
παλαιός = oud, van vroeger
πᾶς (παντός), πᾶσα (πάσης), πᾶν (παντός) = geheel {mnl., vrl., onz.} | ieder | {mv.} alle(n)
ἀποβαίνω = weggaan
πολεμέω = oorlog voeren
σοί, σοι = (aan/voor) jou/je, u {dativus pers. vnw.}
σώφρων (σώφρονος, nom. mv. σώφρονες) = verstandig
τὰ κακά = rampen, ongeluk, ellende
τὸ δεῖπνον = maaltijd
ὑμεῖς, ὑμῶν, ὑμῖν, ὑμᾶς = jullie, u {nom., gen., dat., acc. pers. vnw.}
χαῖρε, χαίρετε = gegroet
`},
{ id: "10", chapter: 10, kind: "les", words: `
ἄδικος = onrechtvaardig
ἀλλά [bij gebiedende wijs] = maar (kom)
ἐλαύνω = (voort)drijven | optrekken, marcheren
τὸ πρόσωπον = gezicht
ἐλπίζω [+ inf.] = hopen, verwachten (te)
πιστός = trouw, betrouwbaar
ἡ δούλη = slavin
ἡ πόλις (acc. πόλιν) = stad
ἡ χείρ (χειρός, dat. mv. χερσί) = hand, arm
θερμός = warm
ἀμφότεροι = beide(n)
πρότερον = eerder {bijwoord}
εὖ = goed {bijwoord}
ἄρχω [+ gen.] = leiden | heersen over
ἴσως = misschien, waarschijnlijk {bijwoord}
καλύπτω = bedekken
κατά [+ gen.] = vanaf…naar beneden
κλα(ί)ω = huilen, wenen (om)
λαμπρός = schitterend
ἡ τελευτή = einde
μανθάνω = leren kennen, begrijpen, vernemen
χωρέω = gaan
ὀλίγος = weinig, gering
πρότερος = eerder, vroeger
τίκτω = baren, ter wereld brengen
τὸ δάκρυον = traan
μέγα = erg, zeer {bijwoord}
`},
{ id: "11", chapter: 11, kind: "les", words: `
ἀπέθανον (inf. ἀποθανεῖν) = ik stierf {aor. van ἀποθνῄσκω}
ἤγαγον (inf. ἀγαγεῖν) = ik bracht, ik leidde {aor. van ἄγω}
διαφθείρω = te gronde richten, vernietigen
εἶπον (inf. εἰπεῖν) = ik zei, ik sprak {aor. bij λέγω zeggen}
τὸ ὄνομα (ὀνόματος) = naam
ἔλαβον (inf. λαβεῖν) = ik pakte, ik nam {aor. van λαμβάνω}
ἔλιπον (inf. λιπεῖν) = ik liet, ik verliet {aor. van λείπω}
τάχα = snel, spoedig {bijwoord}
ἔπεσον (inf. πεσεῖν) = ik viel {aor. bij πίπτω}
θάπτω = begraven
ἤ = of
ἄρχω [+ gen.] = voorgaan, leiden | heersen over | beginnen met
ἦλθον (inf. ἐλθεῖν) = ik kwam, ik ging {aor.}
ἤνεγκον (inf. ἐνεγκεῖν) = ik droeg, ik bracht {aor. bij φέρω}
ὁ φύλαξ (φύλακος) = wachter, bewaker
ἡ ψυχή = ziel, geest, schim | leven
τι (τινος) [zonder accent!] = iets {zelfstandig gebruikt} | enig(e) {bijvoeglijk gebruikt}
κατῆλθον (inf. κατελθεῖν) = ik ging naar beneden, ik daalde af {aor.}
τρέχω = rennen
λυπέω = kwellen, verdriet doen
ὁ ἀδελφός = broer
ἡ χθών (χθονός) = aarde, grond
καταλείπω, aor. κατέλιπον = achterlaten
πρῶτος = eerste
σοῦ, σου = (van) jou/u, jouw/uw {genitivus pers. vnw.}
ταῦτα = dit, dat {onz. meervoud nom. + acc.}
τις (τινος) [zonder accent!] = iemand {zelfstandig gebruikt}, iets | een of ander(e) {bijvoeglijk gebruikt} | enkele(n), sommige(n) {meervoud}
εἶδον (inf. ἰδεῖν) = ik zag {aor. bij ὁράω zien}
σύνειμι [+ dat.] = samenzijn (met), omgaan met
τρέφω, aor. ἔθρεψα = voeden | opvoeden
ἔτεκον (inf. τεκεῖν) = ik baarde, ik bracht ter wereld {aor. van τίκτω}
`},
{ id: "12", chapter: 12, kind: "les", words: `
φυλάττω = bewaken
ἀδικέω = onrecht doen | onrechtvaardig (be)handelen
διαφέρω = verschillen
ἀμείνων (ἀμείνονος) = beter
βέλτιστος = best | zeer goed
μείζων (μείζονος) = groter
βλάπτω = schade toebrengen, benadelen
γιγνώσκω = (leren) kennen | inzien, begrijpen
δειλός = laf | ongelukkig
τάχιστος = snelst | zeer/heel snel
διὰ τοῦτο = daarom {lett.: door dát}
ἔφυγον (inf. φυγεῖν) [+ acc.] = ik vluchtte (voor) {aor. van φεύγω}
ἆρα = {geeft aan dat er een vraagzin volgt}
ἤ = of | dan {na comparativus}
πλείων (onz. πλέον) (πλείονος) = meer
ἡ βουλή = plan, besluit | raad, advies
ὡς τάχιστα = zo snel mogelijk {bijwoord}
ἡ γῆ = aarde | grond, land
κρίνω = oordelen, beoordelen
ἡ τιμή = eer, eerbewijs
βελτίων (βελτίονος) = beter, bekwamer
ἥττων (ἥττονος) = minder, zwakker
κράτιστος = sterkst, best | zeer sterk, zeer goed
κρείττων (κρείττονος) = beter, sterker
μάλιστα = het meest, vooral {bijwoord}
μᾶλλον = meer {bijwoord}
μέγιστος = grootst | zeer groot
ὁ δόλος = list
κακίων (κακίονος) = slechter
ὁ Ζεύς, Διός = Zeus
πλεῖστος = meeste(n) | zeer vele(n)
πλέον = meer {bijwoord}
πότερος; = wie van beide(n)?
σεαυτόν, σεαυτήν = jezelf {accusativus manl., vrl. enk.}
ἡ νύξ (νυκτός) = nacht
ἡ σοφία = wijsheid | slimheid
σκοπέω = bekijken, letten op
ὁ πολέμιος = vijand
σοφός = verstandig, wijs | slim
ὡς = (zo)als
ἔσχον (inf. σχεῖν) = ik had, ik kreeg {aor. van ἔχω}
`},
{ id: "13", chapter: 13, kind: "les", words: `
ἔτι = nog
ἀλλήλους = elkaar {accusativus}
ἀναγκαῖος = noodzakelijk, onvermijdelijk
ὁ πολίτης = burger
βάλλω, aor. ἔβαλον = gooien, werpen
δῆλόν ἐστι(ν) [+ A.c.I.] = het is duidelijk (dat)
οὗτος, αὕτη, τοῦτο = deze/dit, die/dat | hij, zij, het
δῆλος = duidelijk
ἀναγκαῖόν ἐστι(ν) [+ A.c.I.] = het is noodzakelijk/onvermijdelijk (dat)
διώκω = achtervolgen
ἐκεῖνος, ἐκείνη, ἐκεῖνο = die, dat | hij, zij, het (daar)
κάλλιστος = mooist, zeer/heel mooi
λανθάνω [+ acc.] = verborgen zijn voor, ontgaan aan
ὁ αὐτὸς καί = dezelfde als
τὸ σημεῖον = teken
ὅδε, ἥδε, τόδε = deze, dit {mnl., vrl., onz.}
πότερον…ἤ = (of)…of {in een vraagzin}
πρὸς τούτοις = bovendien {lett. bij die dingen}
τὸ αὐτό = hetzelfde
τὸ γόνυ (γόνατος) = knie
τρέχω = rennen
δοκέω, aor. ἔδοξα [+ dat.] = (toe)schijnen (aan)
φρονέω = verstandig zijn
ἄπιστος = ongelofelijk | onbetrouwbaar
χρή [+ inf./A.c.I.] = het is nodig om/dat, het moet
ὅτε = toen, wanneer {voegwoord}
`},
];
